In [2]:
pip install numpy

  Using cached numpy-1.24.2-cp311-cp311-win_amd64.whl (14.8 MB)
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
np.__version__

'1.24.2'

The standard mutable multielement container in Python is the list

In [6]:
L = list(range(20))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [7]:
type(L)

list

In [8]:
type(L[0])

int

In [9]:
L1 = [str(c) for c in L]
L1

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19']

In [10]:
type(L1[0])

str

In [12]:
L2 = [True,'2',3.14,1]
for i in L3:
    print(type(i))

<class 'bool'>
<class 'str'>
<class 'float'>
<class 'int'>


In [13]:
[type(item) for item in L2]

[bool, str, float, int]

The array contains a single pointer to one contiguous block of data. Whereas, the python list contains a pointer to a block of pointers, each of which points to a full Python object.
List: flexible
Array: efficient

In [15]:
#The built-in array module can be used to create dense arrays of a uniform type

import array
L = list(range(10))
A = array.array('i',L)  #'i' is a type code indicating the contents are integer.
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Ways of creating NumPy array**

In [16]:
# 1. Creating array from Python List
import numpy as np

np.array([1,3,5,4,2,5])

array([1, 3, 5, 4, 2, 5])

In [17]:
np.array([12,0.34,-23])

array([ 12.  ,   0.34, -23.  ])

In [18]:
#Explicitly setting the datatype
np.array([23,3.14,5.8],dtype=np.int64)

array([23,  3,  5], dtype=int64)

In [19]:
#initializing a multidimentional array using a list of lists

np.array([range(i,i+2) for i in [2,4,6]])

array([[2, 3],
       [4, 5],
       [6, 7]])

In [20]:
# 2. Creating arrays from Scratch

#array filled with 0s
np.zeros(10,dtype = np.float32)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [21]:
#2-D array filled with 1s
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
# array filled with specific value
np.full((3,3),'love')

array([['love', 'love', 'love'],
       ['love', 'love', 'love'],
       ['love', 'love', 'love']], dtype='<U4')

In [24]:
#Creating an array filled with a linear sequence
#like built-in range function
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [27]:
#an array of 9 values evenly spaced between 2,5
np.linspace(2,5,9)

array([2.   , 2.375, 2.75 , 3.125, 3.5  , 3.875, 4.25 , 4.625, 5.   ])

In [34]:
#Formula used by linspace(a,b,c)
def Linspace(a,b,c):
    L = []
    d = b- a
    val = d/(c-1)
    L.append(a)
    for i in range(c-1):
        a = a+val
        L.append(a)
    return L


In [35]:
Linspace(2,5,9)

[2, 2.375, 2.75, 3.125, 3.5, 3.875, 4.25, 4.625, 5.0]

In [36]:
#Array filled with random values between 0 and 1
np.random.random((3,3))

array([[0.89938498, 0.28897482, 0.47967231],
       [0.67434568, 0.27690704, 0.09640132],
       [0.08912131, 0.0301787 , 0.12593676]])

In [37]:
#Array filed with normally distributed pseudorandom values with mean 0 and std. deviation 1
np.random.normal(0,1,(2,2))

array([[ 2.66890987, -0.54993378],
       [ 1.01515038, -0.34492687]])

In [41]:
#array with random values between 0 and 15
np.random.randint(0,15,(3,3))

array([[ 9,  4,  6],
       [ 6,  2, 11],
       [ 9,  4, 11]])

In [42]:
#identity matrix
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
#creating empty array
np.empty((2,2))

array([[1., 1.],
       [1., 1.]])